-- MySQL Script generated by MySQL Workbench
-- 10/12/15 10:35:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ebabilon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ebabilon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ebabilon` DEFAULT CHARACTER SET utf8 ;
USE `ebabilon` ;

-- -----------------------------------------------------
-- Table `ebabilon`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebabilon`.`users` ;

CREATE TABLE IF NOT EXISTS `ebabilon`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NOT NULL,
  `password` VARCHAR(2555) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `maiden_name` VARCHAR(45) NULL DEFAULT NULL,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT '0',
  `optOutEmail` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `name` (`first_name` ASC, `middle_name` ASC, `last_name` ASC, `maiden_name` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebabilon`.`event_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebabilon`.`event_categories` ;

CREATE TABLE IF NOT EXISTS `ebabilon`.`event_categories` (
  `id_category` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_category`) ,
  UNIQUE INDEX `id_category_UNIQUE` (`id_category` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebabilon`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebabilon`.`events` ;

CREATE TABLE IF NOT EXISTS `ebabilon`.`events` (
  `id_event` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  `place` VARCHAR(255) NULL DEFAULT NULL,
  `admin` INT(11) NOT NULL,
  `category` INT(11) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_event`) ,
  UNIQUE INDEX `id_event_UNIQUE` (`id_event` ASC) ,
  INDEX `admin_idx` (`admin` ASC) ,
  INDEX `event_category_idx` (`category` ASC) ,
  CONSTRAINT `event_admin`
    FOREIGN KEY (`admin`)
    REFERENCES `ebabilon`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `event_category`
    FOREIGN KEY (`category`)
    REFERENCES `ebabilon`.`event_categories` (`id_category`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebabilon`.`attendees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebabilon`.`attendees` ;

CREATE TABLE IF NOT EXISTS `ebabilon`.`attendees` (
  `id_event` INT(11) NOT NULL,
  `id_attendee` INT(11) NOT NULL,
  INDEX `id_event_idx` (`id_event` ASC) ,
  INDEX `id_user_idx` (`id_attendee` ASC) ,
  CONSTRAINT `id_event`
    FOREIGN KEY (`id_event`)
    REFERENCES `ebabilon`.`events` (`id_event`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_attendee`
    FOREIGN KEY (`id_attendee`)
    REFERENCES `ebabilon`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebabilon`.`business_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebabilon`.`business_categories` ;

CREATE TABLE IF NOT EXISTS `ebabilon`.`business_categories` (
  `id_category` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_category`) ,
  UNIQUE INDEX `id_category_UNIQUE` (`id_category` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebabilon`.`businesses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebabilon`.`businesses` ;

CREATE TABLE IF NOT EXISTS `ebabilon`.`businesses` (
  `id_business` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `opHours` VARCHAR(255) NULL DEFAULT NULL,
  `admin` INT(11) NOT NULL,
  `category` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_business`) ,
  UNIQUE INDEX `id_business_UNIQUE` (`id_business` ASC) ,
  INDEX `admin_idx` (`admin` ASC) ,
  INDEX `category_idx` (`category` ASC) ,
  CONSTRAINT `business_admin`
    FOREIGN KEY (`admin`)
    REFERENCES `ebabilon`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `business_category`
    FOREIGN KEY (`category`)
    REFERENCES `ebabilon`.`business_categories` (`id_category`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebabilon`.`followers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebabilon`.`followers` ;

CREATE TABLE IF NOT EXISTS `ebabilon`.`followers` (
  `id_business` INT(11) NOT NULL,
  `id_follower` INT(11) NOT NULL,
  INDEX `business_idx` (`id_business` ASC) ,
  INDEX `follower_idx` (`id_follower` ASC) ,
  CONSTRAINT `business`
    FOREIGN KEY (`id_business`)
    REFERENCES `ebabilon`.`businesses` (`id_business`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `follower`
    FOREIGN KEY (`id_follower`)
    REFERENCES `ebabilon`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebabilon`.`friends_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebabilon`.`friends_categories` ;

CREATE TABLE IF NOT EXISTS `ebabilon`.`friends_categories` (
  `id_category` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_category`) ,
  UNIQUE INDEX `id_category_UNIQUE` (`id_category` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebabilon`.`friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebabilon`.`friends` ;

CREATE TABLE IF NOT EXISTS `ebabilon`.`friends` (
  `id_user` INT(11) NOT NULL,
  `id_friend` INT(11) NOT NULL,
  `category` INT(11) NULL DEFAULT NULL,
  INDEX `category_idx` (`category` ASC) ,
  INDEX `id_user_idx` (`id_user` ASC) ,
  INDEX `id_friend_idx` (`id_friend` ASC) ,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `ebabilon`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_friend`
    FOREIGN KEY (`id_friend`)
    REFERENCES `ebabilon`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `friend_category`
    FOREIGN KEY (`category`)
    REFERENCES `ebabilon`.`friends_categories` (`id_category`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebabilon`.`group_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebabilon`.`group_categories` ;

CREATE TABLE IF NOT EXISTS `ebabilon`.`group_categories` (
  `id_category` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_category`) ,
  UNIQUE INDEX `id_category_UNIQUE` (`id_category` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebabilon`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebabilon`.`groups` ;

CREATE TABLE IF NOT EXISTS `ebabilon`.`groups` (
  `id_group` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `admin` INT(11) NOT NULL,
  `category` INT(11) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_group`) ,
  UNIQUE INDEX `id_group_UNIQUE` (`id_group` ASC) ,
  INDEX `category_idx` (`category` ASC) ,
  INDEX `admin_idx` (`admin` ASC) ,
  CONSTRAINT `group_admin`
    FOREIGN KEY (`admin`)
    REFERENCES `ebabilon`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `group_category`
    FOREIGN KEY (`category`)
    REFERENCES `ebabilon`.`group_categories` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebabilon`.`members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebabilon`.`members` ;

CREATE TABLE IF NOT EXISTS `ebabilon`.`members` (
  `id_group` INT(11) NOT NULL,
  `id_member` INT(11) NOT NULL,
  INDEX `id_group_idx` (`id_group` ASC) ,
  INDEX `id_member_idx` (`id_member` ASC) ,
  CONSTRAINT `id_member`
    FOREIGN KEY (`id_member`)
    REFERENCES `ebabilon`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_group`
    FOREIGN KEY (`id_group`)
    REFERENCES `ebabilon`.`groups` (`id_group`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebabilon`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebabilon`.`posts` ;

CREATE TABLE IF NOT EXISTS `ebabilon`.`posts` (
  `id_post` INT(11) NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(255) NOT NULL,
  `date` DATETIME NOT NULL,
  `author` INT(11) NOT NULL,
  `destination` INT(11) NOT NULL,
  PRIMARY KEY (`id_post`) ,
  UNIQUE INDEX `id_post_UNIQUE` (`id_post` ASC) ,
  INDEX `author_idx` (`author` ASC) ,
  INDEX `destination_idx` (`destination` ASC) ,
  CONSTRAINT `user_author`
    FOREIGN KEY (`author`)
    REFERENCES `ebabilon`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `group_destination`
    FOREIGN KEY (`destination`)
    REFERENCES `ebabilon`.`groups` (`id_group`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `user_destination`
    FOREIGN KEY (`destination`)
    REFERENCES `ebabilon`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `event_destination`
    FOREIGN KEY (`destination`)
    REFERENCES `ebabilon`.`events` (`id_event`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `business_destination`
    FOREIGN KEY (`destination`)
    REFERENCES `ebabilon`.`businesses` (`id_business`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `business_author`
    FOREIGN KEY (`author`)
    REFERENCES `ebabilon`.`businesses` (`id_business`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
